### PR TITLE
Fixing issue with generated methods having invalid characters

### LINKED ISSUE #142: New source generator does not handle generic parameters dependencies
Target class
```C#
public class Controller
{
    public Controller(ILogger<Controller> logger) { ... }
}
```

Test class
```C#
[ConstructorTests(typeof(Controller))]
public class ControllerTests
{

}
```

Observed, the generated test names contain `<` and `>` causing the test method name to be invalid.

Expetected: The source generator should never generate invalid method names.

### PR DESCRIPTION
**Pull request by Keboo**
When an identifier is invalid, the generator will now strip out all invalid characters.

Fixes #142

### CODE REVIEW

File: Moq.AutoMocker.TestGenerator/TestNameBuilder.cs [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    {
+        int testNameIndex = 0;
+        for (string testName = $"{testClass.Sut!.Name}Constructor_WithNull{test.NullTypeName}_ThrowsArgumentNullException";
+            ;
+            testName = $"{testClass.Sut!.Name}Constructor_WithNull{test.NullTypeName}{++testNameIndex}_ThrowsArgumentNullException")
+        {
+            if (!SyntaxFacts.IsValidIdentifier(testName))
+            {
+                StringBuilder sb = new(testName.Length);
+                for (int i = 0; i < testName.Length; i++)
```
Comment (adamhewitt627) [inline Moq.AutoMocker.TestGenerator/TestNameBuilder.cs:18]: Thoughts on making this a:

testName.SkipWhile(NotStart).Where(IsPart)

**Review by adamhewitt627 — APPROVED** [review]
